/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { HELIUS_TEST_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_VALUE_DISCRIMINATOR = 3;

export function getSetValueDiscriminatorBytes() {
  return getU8Encoder().encode(SET_VALUE_DISCRIMINATOR);
}

export type SetValueInstruction<
  TProgram extends string = typeof HELIUS_TEST_PROGRAM_ADDRESS,
  TAccountHeliusTest extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountHeliusTest extends string
        ? WritableAccount<TAccountHeliusTest>
        : TAccountHeliusTest,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SetValueInstructionData = {
  discriminator: number;
  newValue: bigint;
};

export type SetValueInstructionDataArgs = { newValue: number | bigint };

export function getSetValueInstructionDataEncoder(): Encoder<SetValueInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['newValue', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_VALUE_DISCRIMINATOR }),
  );
}

export function getSetValueInstructionDataDecoder(): Decoder<SetValueInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['newValue', getU64Decoder()],
  ]);
}

export function getSetValueInstructionDataCodec(): Codec<
  SetValueInstructionDataArgs,
  SetValueInstructionData
> {
  return combineCodec(
    getSetValueInstructionDataEncoder(),
    getSetValueInstructionDataDecoder(),
  );
}

export type SetValueInput<
  TAccountHeliusTest extends string = string,
  TAccountAuthority extends string = string,
> = {
  /** Counter account to update */
  heliusTest: Address<TAccountHeliusTest>;
  /** Authority account */
  authority: TransactionSigner<TAccountAuthority>;
  newValue: SetValueInstructionDataArgs['newValue'];
};

export function getSetValueInstruction<
  TAccountHeliusTest extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof HELIUS_TEST_PROGRAM_ADDRESS,
>(
  input: SetValueInput<TAccountHeliusTest, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): SetValueInstruction<TProgramAddress, TAccountHeliusTest, TAccountAuthority> {
  // Program address.
  const programAddress = config?.programAddress ?? HELIUS_TEST_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    heliusTest: { value: input.heliusTest ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.heliusTest),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getSetValueInstructionDataEncoder().encode(
      args as SetValueInstructionDataArgs,
    ),
  } as SetValueInstruction<
    TProgramAddress,
    TAccountHeliusTest,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedSetValueInstruction<
  TProgram extends string = typeof HELIUS_TEST_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Counter account to update */
    heliusTest: TAccountMetas[0];
    /** Authority account */
    authority: TAccountMetas[1];
  };
  data: SetValueInstructionData;
};

export function parseSetValueInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedSetValueInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      heliusTest: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getSetValueInstructionDataDecoder().decode(instruction.data),
  };
}
