/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type CreateAddressInfoInstructionData = {
  name: ReadonlyUint8Array;
  houseNumber: number;
  street: ReadonlyUint8Array;
  city: ReadonlyUint8Array;
};

export type CreateAddressInfoInstructionDataArgs =
  CreateAddressInfoInstructionData;

export function getCreateAddressInfoInstructionDataEncoder(): Encoder<CreateAddressInfoInstructionDataArgs> {
  return getStructEncoder([
    ['name', fixEncoderSize(getBytesEncoder(), 50)],
    ['houseNumber', getU8Encoder()],
    ['street', fixEncoderSize(getBytesEncoder(), 50)],
    ['city', fixEncoderSize(getBytesEncoder(), 50)],
  ]);
}

export function getCreateAddressInfoInstructionDataDecoder(): Decoder<CreateAddressInfoInstructionData> {
  return getStructDecoder([
    ['name', fixDecoderSize(getBytesDecoder(), 50)],
    ['houseNumber', getU8Decoder()],
    ['street', fixDecoderSize(getBytesDecoder(), 50)],
    ['city', fixDecoderSize(getBytesDecoder(), 50)],
  ]);
}

export function getCreateAddressInfoInstructionDataCodec(): Codec<
  CreateAddressInfoInstructionDataArgs,
  CreateAddressInfoInstructionData
> {
  return combineCodec(
    getCreateAddressInfoInstructionDataEncoder(),
    getCreateAddressInfoInstructionDataDecoder(),
  );
}
