/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
} from '@solana/kit';
import { CREATE_TOKEN_PROGRAM_ADDRESS } from '../programs';

export const CREATE_PDA_DISCRIMINATOR = 0;

export function getCreatePdaDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_PDA_DISCRIMINATOR);
}

export type CreatePdaInstruction<
  TProgram extends string = typeof CREATE_TOKEN_PROGRAM_ADDRESS,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<TRemainingAccounts>;

export type CreatePdaInstructionData = { discriminator: number };

export type CreatePdaInstructionDataArgs = {};

export function getCreatePdaInstructionDataEncoder(): Encoder<CreatePdaInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: CREATE_PDA_DISCRIMINATOR }),
  );
}

export function getCreatePdaInstructionDataDecoder(): Decoder<CreatePdaInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getCreatePdaInstructionDataCodec(): Codec<
  CreatePdaInstructionDataArgs,
  CreatePdaInstructionData
> {
  return combineCodec(
    getCreatePdaInstructionDataEncoder(),
    getCreatePdaInstructionDataDecoder(),
  );
}

export type CreatePdaInput = {};

export function getCreatePdaInstruction<
  TProgramAddress extends Address = typeof CREATE_TOKEN_PROGRAM_ADDRESS,
>(config?: {
  programAddress?: TProgramAddress;
}): CreatePdaInstruction<TProgramAddress> {
  // Program address.
  const programAddress = config?.programAddress ?? CREATE_TOKEN_PROGRAM_ADDRESS;

  const instruction = {
    programAddress,
    data: getCreatePdaInstructionDataEncoder().encode({}),
  } as CreatePdaInstruction<TProgramAddress>;

  return instruction;
}

export type ParsedCreatePdaInstruction<
  TProgram extends string = typeof CREATE_TOKEN_PROGRAM_ADDRESS,
> = {
  programAddress: Address<TProgram>;
  data: CreatePdaInstructionData;
};

export function parseCreatePdaInstruction<TProgram extends string>(
  instruction: IInstruction<TProgram> & IInstructionWithData<Uint8Array>,
): ParsedCreatePdaInstruction<TProgram> {
  return {
    programAddress: instruction.programAddress,
    data: getCreatePdaInstructionDataDecoder().decode(instruction.data),
  };
}
