/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { COUNTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const DECREASE_DISCRIMINATOR = 2;

export function getDecreaseDiscriminatorBytes() {
  return getU8Encoder().encode(DECREASE_DISCRIMINATOR);
}

export type DecreaseInstruction<
  TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountCounter extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountCounter extends string
        ? WritableAccount<TAccountCounter>
        : TAccountCounter,
      ...TRemainingAccounts,
    ]
  >;

export type DecreaseInstructionData = { discriminator: number };

export type DecreaseInstructionDataArgs = {};

export function getDecreaseInstructionDataEncoder(): Encoder<DecreaseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: DECREASE_DISCRIMINATOR }),
  );
}

export function getDecreaseInstructionDataDecoder(): Decoder<DecreaseInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getDecreaseInstructionDataCodec(): Codec<
  DecreaseInstructionDataArgs,
  DecreaseInstructionData
> {
  return combineCodec(
    getDecreaseInstructionDataEncoder(),
    getDecreaseInstructionDataDecoder(),
  );
}

export type DecreaseInput<
  TAccountAuthority extends string = string,
  TAccountCounter extends string = string,
> = {
  /** Counter authority */
  authority: TransactionSigner<TAccountAuthority>;
  /** The counter account */
  counter: Address<TAccountCounter>;
};

export function getDecreaseInstruction<
  TAccountAuthority extends string,
  TAccountCounter extends string,
  TProgramAddress extends Address = typeof COUNTER_PROGRAM_ADDRESS,
>(
  input: DecreaseInput<TAccountAuthority, TAccountCounter>,
  config?: { programAddress?: TProgramAddress },
): DecreaseInstruction<TProgramAddress, TAccountAuthority, TAccountCounter> {
  // Program address.
  const programAddress = config?.programAddress ?? COUNTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    counter: { value: input.counter ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.counter),
    ],
    programAddress,
    data: getDecreaseInstructionDataEncoder().encode({}),
  } as DecreaseInstruction<TProgramAddress, TAccountAuthority, TAccountCounter>;

  return instruction;
}

export type ParsedDecreaseInstruction<
  TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Counter authority */
    authority: TAccountMetas[0];
    /** The counter account */
    counter: TAccountMetas[1];
  };
  data: DecreaseInstructionData;
};

export function parseDecreaseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedDecreaseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      counter: getNextAccount(),
    },
    data: getDecreaseInstructionDataDecoder().decode(instruction.data),
  };
}
