/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { COUNTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INCREASE_DISCRIMINATOR = 1;

export function getIncreaseDiscriminatorBytes() {
  return getU8Encoder().encode(INCREASE_DISCRIMINATOR);
}

export type IncreaseInstruction<
  TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountCounter extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountCounter extends string
        ? WritableAccount<TAccountCounter>
        : TAccountCounter,
      ...TRemainingAccounts,
    ]
  >;

export type IncreaseInstructionData = { discriminator: number };

export type IncreaseInstructionDataArgs = {};

export function getIncreaseInstructionDataEncoder(): Encoder<IncreaseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: INCREASE_DISCRIMINATOR }),
  );
}

export function getIncreaseInstructionDataDecoder(): Decoder<IncreaseInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getIncreaseInstructionDataCodec(): Codec<
  IncreaseInstructionDataArgs,
  IncreaseInstructionData
> {
  return combineCodec(
    getIncreaseInstructionDataEncoder(),
    getIncreaseInstructionDataDecoder(),
  );
}

export type IncreaseInput<
  TAccountAuthority extends string = string,
  TAccountCounter extends string = string,
> = {
  /** Counter authority */
  authority: TransactionSigner<TAccountAuthority>;
  /** The counter account */
  counter: Address<TAccountCounter>;
};

export function getIncreaseInstruction<
  TAccountAuthority extends string,
  TAccountCounter extends string,
  TProgramAddress extends Address = typeof COUNTER_PROGRAM_ADDRESS,
>(
  input: IncreaseInput<TAccountAuthority, TAccountCounter>,
  config?: { programAddress?: TProgramAddress },
): IncreaseInstruction<TProgramAddress, TAccountAuthority, TAccountCounter> {
  // Program address.
  const programAddress = config?.programAddress ?? COUNTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    counter: { value: input.counter ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.counter),
    ],
    programAddress,
    data: getIncreaseInstructionDataEncoder().encode({}),
  } as IncreaseInstruction<TProgramAddress, TAccountAuthority, TAccountCounter>;

  return instruction;
}

export type ParsedIncreaseInstruction<
  TProgram extends string = typeof COUNTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Counter authority */
    authority: TAccountMetas[0];
    /** The counter account */
    counter: TAccountMetas[1];
  };
  data: IncreaseInstructionData;
};

export function parseIncreaseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedIncreaseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      counter: getNextAccount(),
    },
    data: getIncreaseInstructionDataDecoder().decode(instruction.data),
  };
}
