/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedDecrementInstruction,
  type ParsedIncrementInstruction,
  type ParsedInitializeInstruction,
  type ParsedResetInstruction,
  type ParsedSetValueInstruction,
} from '../instructions';

export const MY_COUNTER_PROGRAM_ADDRESS =
  '5fZEPFcYZQFkAGhTLtVaUd8ojnG9znjEk9TPDXwEnVAU' as Address<'5fZEPFcYZQFkAGhTLtVaUd8ojnG9znjEk9TPDXwEnVAU'>;

export enum MyCounterAccount {
  Counter,
}

export enum MyCounterInstruction {
  Initialize,
  Increment,
  Decrement,
  SetValue,
  Reset,
}

export function identifyMyCounterInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): MyCounterInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return MyCounterInstruction.Initialize;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return MyCounterInstruction.Increment;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return MyCounterInstruction.Decrement;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return MyCounterInstruction.SetValue;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return MyCounterInstruction.Reset;
  }
  throw new Error(
    'The provided instruction could not be identified as a myCounter instruction.',
  );
}

export type ParsedMyCounterInstruction<
  TProgram extends string = '5fZEPFcYZQFkAGhTLtVaUd8ojnG9znjEk9TPDXwEnVAU',
> =
  | ({
      instructionType: MyCounterInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: MyCounterInstruction.Increment;
    } & ParsedIncrementInstruction<TProgram>)
  | ({
      instructionType: MyCounterInstruction.Decrement;
    } & ParsedDecrementInstruction<TProgram>)
  | ({
      instructionType: MyCounterInstruction.SetValue;
    } & ParsedSetValueInstruction<TProgram>)
  | ({
      instructionType: MyCounterInstruction.Reset;
    } & ParsedResetInstruction<TProgram>);
