/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLEANUP_OLD_EPOCH_OUTCOME_DISCRIMINATOR = 17;

export function getCleanupOldEpochOutcomeDiscriminatorBytes() {
  return getU8Encoder().encode(CLEANUP_OLD_EPOCH_OUTCOME_DISCRIMINATOR);
}

export type CleanupOldEpochOutcomeInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountEpochOutcome extends string | IAccountMeta<string> = string,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochOutcome extends string
        ? WritableAccount<TAccountEpochOutcome>
        : TAccountEpochOutcome,
      TAccountGlobalGameState extends string
        ? ReadonlyAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type CleanupOldEpochOutcomeInstructionData = { discriminator: number };

export type CleanupOldEpochOutcomeInstructionDataArgs = {};

export function getCleanupOldEpochOutcomeInstructionDataEncoder(): Encoder<CleanupOldEpochOutcomeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: CLEANUP_OLD_EPOCH_OUTCOME_DISCRIMINATOR,
    }),
  );
}

export function getCleanupOldEpochOutcomeInstructionDataDecoder(): Decoder<CleanupOldEpochOutcomeInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getCleanupOldEpochOutcomeInstructionDataCodec(): Codec<
  CleanupOldEpochOutcomeInstructionDataArgs,
  CleanupOldEpochOutcomeInstructionData
> {
  return combineCodec(
    getCleanupOldEpochOutcomeInstructionDataEncoder(),
    getCleanupOldEpochOutcomeInstructionDataDecoder(),
  );
}

export type CleanupOldEpochOutcomeInput<
  TAccountEpochOutcome extends string = string,
  TAccountGlobalGameState extends string = string,
  TAccountAdmin extends string = string,
> = {
  /** Epoch outcome to clean */
  epochOutcome: Address<TAccountEpochOutcome>;
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Admin authority */
  admin: TransactionSigner<TAccountAdmin>;
};

export function getCleanupOldEpochOutcomeInstruction<
  TAccountEpochOutcome extends string,
  TAccountGlobalGameState extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: CleanupOldEpochOutcomeInput<
    TAccountEpochOutcome,
    TAccountGlobalGameState,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress },
): CleanupOldEpochOutcomeInstruction<
  TProgramAddress,
  TAccountEpochOutcome,
  TAccountGlobalGameState,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochOutcome: { value: input.epochOutcome ?? null, isWritable: true },
    globalGameState: {
      value: input.globalGameState ?? null,
      isWritable: false,
    },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochOutcome),
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getCleanupOldEpochOutcomeInstructionDataEncoder().encode({}),
  } as CleanupOldEpochOutcomeInstruction<
    TProgramAddress,
    TAccountEpochOutcome,
    TAccountGlobalGameState,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedCleanupOldEpochOutcomeInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Epoch outcome to clean */
    epochOutcome: TAccountMetas[0];
    /** Global game state account */
    globalGameState: TAccountMetas[1];
    /** Admin authority */
    admin: TAccountMetas[2];
  };
  data: CleanupOldEpochOutcomeInstructionData;
};

export function parseCleanupOldEpochOutcomeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedCleanupOldEpochOutcomeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochOutcome: getNextAccount(),
      globalGameState: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getCleanupOldEpochOutcomeInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
