/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_PLAYER_ACCOUNT_DISCRIMINATOR = 3;

export function getClosePlayerAccountDiscriminatorBytes() {
  return getU8Encoder().encode(CLOSE_PLAYER_ACCOUNT_DISCRIMINATOR);
}

export type ClosePlayerAccountInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountPlayerState extends string | IAccountMeta<string> = string,
  TAccountPlayer extends string | IAccountMeta<string> = string,
  TAccountReceiver extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPlayerState extends string
        ? WritableAccount<TAccountPlayerState>
        : TAccountPlayerState,
      TAccountPlayer extends string
        ? ReadonlySignerAccount<TAccountPlayer> &
            IAccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountReceiver extends string
        ? WritableAccount<TAccountReceiver>
        : TAccountReceiver,
      ...TRemainingAccounts,
    ]
  >;

export type ClosePlayerAccountInstructionData = { discriminator: number };

export type ClosePlayerAccountInstructionDataArgs = {};

export function getClosePlayerAccountInstructionDataEncoder(): Encoder<ClosePlayerAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_PLAYER_ACCOUNT_DISCRIMINATOR,
    }),
  );
}

export function getClosePlayerAccountInstructionDataDecoder(): Decoder<ClosePlayerAccountInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getClosePlayerAccountInstructionDataCodec(): Codec<
  ClosePlayerAccountInstructionDataArgs,
  ClosePlayerAccountInstructionData
> {
  return combineCodec(
    getClosePlayerAccountInstructionDataEncoder(),
    getClosePlayerAccountInstructionDataDecoder(),
  );
}

export type ClosePlayerAccountInput<
  TAccountPlayerState extends string = string,
  TAccountPlayer extends string = string,
  TAccountReceiver extends string = string,
> = {
  /** Player state account to close */
  playerState: Address<TAccountPlayerState>;
  /** Player account */
  player: TransactionSigner<TAccountPlayer>;
  /** Account to receive rent */
  receiver: Address<TAccountReceiver>;
};

export function getClosePlayerAccountInstruction<
  TAccountPlayerState extends string,
  TAccountPlayer extends string,
  TAccountReceiver extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: ClosePlayerAccountInput<
    TAccountPlayerState,
    TAccountPlayer,
    TAccountReceiver
  >,
  config?: { programAddress?: TProgramAddress },
): ClosePlayerAccountInstruction<
  TProgramAddress,
  TAccountPlayerState,
  TAccountPlayer,
  TAccountReceiver
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    playerState: { value: input.playerState ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: false },
    receiver: { value: input.receiver ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.playerState),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.receiver),
    ],
    programAddress,
    data: getClosePlayerAccountInstructionDataEncoder().encode({}),
  } as ClosePlayerAccountInstruction<
    TProgramAddress,
    TAccountPlayerState,
    TAccountPlayer,
    TAccountReceiver
  >;

  return instruction;
}

export type ParsedClosePlayerAccountInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Player state account to close */
    playerState: TAccountMetas[0];
    /** Player account */
    player: TAccountMetas[1];
    /** Account to receive rent */
    receiver: TAccountMetas[2];
  };
  data: ClosePlayerAccountInstructionData;
};

export function parseClosePlayerAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedClosePlayerAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      playerState: getNextAccount(),
      player: getNextAccount(),
      receiver: getNextAccount(),
    },
    data: getClosePlayerAccountInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
