/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const FINALIZE_RNG_DISCRIMINATOR = 11;

export function getFinalizeRngDiscriminatorBytes() {
  return getU8Encoder().encode(FINALIZE_RNG_DISCRIMINATOR);
}

export type FinalizeRngInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountRngState extends string | IAccountMeta<string> = string,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountRngAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountRngState extends string
        ? WritableAccount<TAccountRngState>
        : TAccountRngState,
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountRngAuthority extends string
        ? ReadonlySignerAccount<TAccountRngAuthority> &
            IAccountSignerMeta<TAccountRngAuthority>
        : TAccountRngAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type FinalizeRngInstructionData = { discriminator: number };

export type FinalizeRngInstructionDataArgs = {};

export function getFinalizeRngInstructionDataEncoder(): Encoder<FinalizeRngInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: FINALIZE_RNG_DISCRIMINATOR }),
  );
}

export function getFinalizeRngInstructionDataDecoder(): Decoder<FinalizeRngInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getFinalizeRngInstructionDataCodec(): Codec<
  FinalizeRngInstructionDataArgs,
  FinalizeRngInstructionData
> {
  return combineCodec(
    getFinalizeRngInstructionDataEncoder(),
    getFinalizeRngInstructionDataDecoder(),
  );
}

export type FinalizeRngInput<
  TAccountRngState extends string = string,
  TAccountGlobalGameState extends string = string,
  TAccountRngAuthority extends string = string,
> = {
  /** RNG state account */
  rngState: Address<TAccountRngState>;
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** RNG authority */
  rngAuthority: TransactionSigner<TAccountRngAuthority>;
};

export function getFinalizeRngInstruction<
  TAccountRngState extends string,
  TAccountGlobalGameState extends string,
  TAccountRngAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: FinalizeRngInput<
    TAccountRngState,
    TAccountGlobalGameState,
    TAccountRngAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): FinalizeRngInstruction<
  TProgramAddress,
  TAccountRngState,
  TAccountGlobalGameState,
  TAccountRngAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    rngState: { value: input.rngState ?? null, isWritable: true },
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    rngAuthority: { value: input.rngAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.rngState),
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.rngAuthority),
    ],
    programAddress,
    data: getFinalizeRngInstructionDataEncoder().encode({}),
  } as FinalizeRngInstruction<
    TProgramAddress,
    TAccountRngState,
    TAccountGlobalGameState,
    TAccountRngAuthority
  >;

  return instruction;
}

export type ParsedFinalizeRngInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** RNG state account */
    rngState: TAccountMetas[0];
    /** Global game state account */
    globalGameState: TAccountMetas[1];
    /** RNG authority */
    rngAuthority: TAccountMetas[2];
  };
  data: FinalizeRngInstructionData;
};

export function parseFinalizeRngInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedFinalizeRngInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      rngState: getNextAccount(),
      globalGameState: getNextAccount(),
      rngAuthority: getNextAccount(),
    },
    data: getFinalizeRngInstructionDataDecoder().decode(instruction.data),
  };
}
