/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_CRITICAL_P_D_AS_DISCRIMINATOR = 1;

export function getInitializeCriticalPDAsDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_CRITICAL_P_D_AS_DISCRIMINATOR);
}

export type InitializeCriticalPDAsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountRngState extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountRngState extends string
        ? WritableAccount<TAccountRngState>
        : TAccountRngState,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeCriticalPDAsInstructionData = { discriminator: number };

export type InitializeCriticalPDAsInstructionDataArgs = {};

export function getInitializeCriticalPDAsInstructionDataEncoder(): Encoder<InitializeCriticalPDAsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_CRITICAL_P_D_AS_DISCRIMINATOR,
    }),
  );
}

export function getInitializeCriticalPDAsInstructionDataDecoder(): Decoder<InitializeCriticalPDAsInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getInitializeCriticalPDAsInstructionDataCodec(): Codec<
  InitializeCriticalPDAsInstructionDataArgs,
  InitializeCriticalPDAsInstructionData
> {
  return combineCodec(
    getInitializeCriticalPDAsInstructionDataEncoder(),
    getInitializeCriticalPDAsInstructionDataDecoder(),
  );
}

export type InitializeCriticalPDAsInput<
  TAccountGlobalGameState extends string = string,
  TAccountTreasury extends string = string,
  TAccountRngState extends string = string,
  TAccountAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** RNG state account */
  rngState: Address<TAccountRngState>;
  /** System authority */
  authority: TransactionSigner<TAccountAuthority>;
};

export function getInitializeCriticalPDAsInstruction<
  TAccountGlobalGameState extends string,
  TAccountTreasury extends string,
  TAccountRngState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: InitializeCriticalPDAsInput<
    TAccountGlobalGameState,
    TAccountTreasury,
    TAccountRngState,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeCriticalPDAsInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountTreasury,
  TAccountRngState,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    rngState: { value: input.rngState ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.rngState),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getInitializeCriticalPDAsInstructionDataEncoder().encode({}),
  } as InitializeCriticalPDAsInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountTreasury,
    TAccountRngState,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedInitializeCriticalPDAsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Treasury account */
    treasury: TAccountMetas[1];
    /** RNG state account */
    rngState: TAccountMetas[2];
    /** System authority */
    authority: TAccountMetas[3];
  };
  data: InitializeCriticalPDAsInstructionData;
};

export function parseInitializeCriticalPDAsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedInitializeCriticalPDAsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      treasury: getNextAccount(),
      rngState: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getInitializeCriticalPDAsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
