/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const PLACE_BET_DISCRIMINATOR = 8;

export function getPlaceBetDiscriminatorBytes() {
  return getU8Encoder().encode(PLACE_BET_DISCRIMINATOR);
}

export type PlaceBetInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountBetBatch extends string | IAccountMeta<string> = string,
  TAccountPlayerState extends string | IAccountMeta<string> = string,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountPlayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountBetBatch extends string
        ? WritableAccount<TAccountBetBatch>
        : TAccountBetBatch,
      TAccountPlayerState extends string
        ? WritableAccount<TAccountPlayerState>
        : TAccountPlayerState,
      TAccountGlobalGameState extends string
        ? ReadonlyAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountPlayer extends string
        ? ReadonlySignerAccount<TAccountPlayer> &
            IAccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlaceBetInstructionData = { discriminator: number };

export type PlaceBetInstructionDataArgs = {};

export function getPlaceBetInstructionDataEncoder(): Encoder<PlaceBetInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: PLACE_BET_DISCRIMINATOR }),
  );
}

export function getPlaceBetInstructionDataDecoder(): Decoder<PlaceBetInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getPlaceBetInstructionDataCodec(): Codec<
  PlaceBetInstructionDataArgs,
  PlaceBetInstructionData
> {
  return combineCodec(
    getPlaceBetInstructionDataEncoder(),
    getPlaceBetInstructionDataDecoder(),
  );
}

export type PlaceBetInput<
  TAccountBetBatch extends string = string,
  TAccountPlayerState extends string = string,
  TAccountGlobalGameState extends string = string,
  TAccountPlayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Bet batch account */
  betBatch: Address<TAccountBetBatch>;
  /** Player state account */
  playerState: Address<TAccountPlayerState>;
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Player account */
  player: TransactionSigner<TAccountPlayer>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getPlaceBetInstruction<
  TAccountBetBatch extends string,
  TAccountPlayerState extends string,
  TAccountGlobalGameState extends string,
  TAccountPlayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: PlaceBetInput<
    TAccountBetBatch,
    TAccountPlayerState,
    TAccountGlobalGameState,
    TAccountPlayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PlaceBetInstruction<
  TProgramAddress,
  TAccountBetBatch,
  TAccountPlayerState,
  TAccountGlobalGameState,
  TAccountPlayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    betBatch: { value: input.betBatch ?? null, isWritable: true },
    playerState: { value: input.playerState ?? null, isWritable: true },
    globalGameState: {
      value: input.globalGameState ?? null,
      isWritable: false,
    },
    player: { value: input.player ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.betBatch),
      getAccountMeta(accounts.playerState),
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPlaceBetInstructionDataEncoder().encode({}),
  } as PlaceBetInstruction<
    TProgramAddress,
    TAccountBetBatch,
    TAccountPlayerState,
    TAccountGlobalGameState,
    TAccountPlayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedPlaceBetInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Bet batch account */
    betBatch: TAccountMetas[0];
    /** Player state account */
    playerState: TAccountMetas[1];
    /** Global game state account */
    globalGameState: TAccountMetas[2];
    /** Player account */
    player: TAccountMetas[3];
    /** System program */
    systemProgram: TAccountMetas[4];
  };
  data: PlaceBetInstructionData;
};

export function parsePlaceBetInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedPlaceBetInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      betBatch: getNextAccount(),
      playerState: getNextAccount(),
      globalGameState: getNextAccount(),
      player: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPlaceBetInstructionDataDecoder().decode(instruction.data),
  };
}
