/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESUME_OPERATIONS_DISCRIMINATOR = 24;

export function getResumeOperationsDiscriminatorBytes() {
  return getU8Encoder().encode(RESUME_OPERATIONS_DISCRIMINATOR);
}

export type ResumeOperationsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountEmergencyAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountEmergencyAuthority extends string
        ? ReadonlySignerAccount<TAccountEmergencyAuthority> &
            IAccountSignerMeta<TAccountEmergencyAuthority>
        : TAccountEmergencyAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ResumeOperationsInstructionData = { discriminator: number };

export type ResumeOperationsInstructionDataArgs = {};

export function getResumeOperationsInstructionDataEncoder(): Encoder<ResumeOperationsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: RESUME_OPERATIONS_DISCRIMINATOR }),
  );
}

export function getResumeOperationsInstructionDataDecoder(): Decoder<ResumeOperationsInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getResumeOperationsInstructionDataCodec(): Codec<
  ResumeOperationsInstructionDataArgs,
  ResumeOperationsInstructionData
> {
  return combineCodec(
    getResumeOperationsInstructionDataEncoder(),
    getResumeOperationsInstructionDataDecoder(),
  );
}

export type ResumeOperationsInput<
  TAccountGlobalGameState extends string = string,
  TAccountEmergencyAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Emergency authority */
  emergencyAuthority: TransactionSigner<TAccountEmergencyAuthority>;
};

export function getResumeOperationsInstruction<
  TAccountGlobalGameState extends string,
  TAccountEmergencyAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: ResumeOperationsInput<
    TAccountGlobalGameState,
    TAccountEmergencyAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): ResumeOperationsInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountEmergencyAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    emergencyAuthority: {
      value: input.emergencyAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.emergencyAuthority),
    ],
    programAddress,
    data: getResumeOperationsInstructionDataEncoder().encode({}),
  } as ResumeOperationsInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountEmergencyAuthority
  >;

  return instruction;
}

export type ParsedResumeOperationsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Emergency authority */
    emergencyAuthority: TAccountMetas[1];
  };
  data: ResumeOperationsInstructionData;
};

export function parseResumeOperationsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedResumeOperationsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      emergencyAuthority: getNextAccount(),
    },
    data: getResumeOperationsInstructionDataDecoder().decode(instruction.data),
  };
}
