/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESUME_GAME_DISCRIMINATOR = 26;

export function getResumeGameDiscriminatorBytes() {
  return getU8Encoder().encode(RESUME_GAME_DISCRIMINATOR);
}

export type ResumeGameInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ResumeGameInstructionData = { discriminator: number };

export type ResumeGameInstructionDataArgs = {};

export function getResumeGameInstructionDataEncoder(): Encoder<ResumeGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: RESUME_GAME_DISCRIMINATOR }),
  );
}

export function getResumeGameInstructionDataDecoder(): Decoder<ResumeGameInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getResumeGameInstructionDataCodec(): Codec<
  ResumeGameInstructionDataArgs,
  ResumeGameInstructionData
> {
  return combineCodec(
    getResumeGameInstructionDataEncoder(),
    getResumeGameInstructionDataDecoder(),
  );
}

export type ResumeGameInput<
  TAccountGlobalGameState extends string = string,
  TAccountAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Authority account */
  authority: TransactionSigner<TAccountAuthority>;
};

export function getResumeGameInstruction<
  TAccountGlobalGameState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: ResumeGameInput<TAccountGlobalGameState, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): ResumeGameInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getResumeGameInstructionDataEncoder().encode({}),
  } as ResumeGameInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedResumeGameInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Authority account */
    authority: TAccountMetas[1];
  };
  data: ResumeGameInstructionData;
};

export function parseResumeGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedResumeGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getResumeGameInstructionDataDecoder().decode(instruction.data),
  };
}
