/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SECURE_AUTO_ROLL_DISCRIMINATOR = 9;

export function getSecureAutoRollDiscriminatorBytes() {
  return getU8Encoder().encode(SECURE_AUTO_ROLL_DISCRIMINATOR);
}

export type SecureAutoRollInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountBonusState extends string | IAccountMeta<string> = string,
  TAccountRngState extends string | IAccountMeta<string> = string,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountRngAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountBonusState extends string
        ? WritableAccount<TAccountBonusState>
        : TAccountBonusState,
      TAccountRngState extends string
        ? WritableAccount<TAccountRngState>
        : TAccountRngState,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountRngAuthority extends string
        ? ReadonlySignerAccount<TAccountRngAuthority> &
            IAccountSignerMeta<TAccountRngAuthority>
        : TAccountRngAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SecureAutoRollInstructionData = { discriminator: number };

export type SecureAutoRollInstructionDataArgs = {};

export function getSecureAutoRollInstructionDataEncoder(): Encoder<SecureAutoRollInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: SECURE_AUTO_ROLL_DISCRIMINATOR }),
  );
}

export function getSecureAutoRollInstructionDataDecoder(): Decoder<SecureAutoRollInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getSecureAutoRollInstructionDataCodec(): Codec<
  SecureAutoRollInstructionDataArgs,
  SecureAutoRollInstructionData
> {
  return combineCodec(
    getSecureAutoRollInstructionDataEncoder(),
    getSecureAutoRollInstructionDataDecoder(),
  );
}

export type SecureAutoRollInput<
  TAccountGlobalGameState extends string = string,
  TAccountBonusState extends string = string,
  TAccountRngState extends string = string,
  TAccountTreasury extends string = string,
  TAccountRngAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Bonus state account */
  bonusState: Address<TAccountBonusState>;
  /** RNG state account */
  rngState: Address<TAccountRngState>;
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** RNG authority */
  rngAuthority: TransactionSigner<TAccountRngAuthority>;
};

export function getSecureAutoRollInstruction<
  TAccountGlobalGameState extends string,
  TAccountBonusState extends string,
  TAccountRngState extends string,
  TAccountTreasury extends string,
  TAccountRngAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: SecureAutoRollInput<
    TAccountGlobalGameState,
    TAccountBonusState,
    TAccountRngState,
    TAccountTreasury,
    TAccountRngAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): SecureAutoRollInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountBonusState,
  TAccountRngState,
  TAccountTreasury,
  TAccountRngAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    bonusState: { value: input.bonusState ?? null, isWritable: true },
    rngState: { value: input.rngState ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    rngAuthority: { value: input.rngAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.bonusState),
      getAccountMeta(accounts.rngState),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.rngAuthority),
    ],
    programAddress,
    data: getSecureAutoRollInstructionDataEncoder().encode({}),
  } as SecureAutoRollInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountBonusState,
    TAccountRngState,
    TAccountTreasury,
    TAccountRngAuthority
  >;

  return instruction;
}

export type ParsedSecureAutoRollInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Bonus state account */
    bonusState: TAccountMetas[1];
    /** RNG state account */
    rngState: TAccountMetas[2];
    /** Treasury account */
    treasury: TAccountMetas[3];
    /** RNG authority */
    rngAuthority: TAccountMetas[4];
  };
  data: SecureAutoRollInstructionData;
};

export function parseSecureAutoRollInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedSecureAutoRollInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      bonusState: getNextAccount(),
      rngState: getNextAccount(),
      treasury: getNextAccount(),
      rngAuthority: getNextAccount(),
    },
    data: getSecureAutoRollInstructionDataDecoder().decode(instruction.data),
  };
}
