/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SETTLE_REALIZABLE_BETS_DISCRIMINATOR = 13;

export function getSettleRealizableBetsDiscriminatorBytes() {
  return getU8Encoder().encode(SETTLE_REALIZABLE_BETS_DISCRIMINATOR);
}

export type SettleRealizableBetsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SettleRealizableBetsInstructionData = { discriminator: number };

export type SettleRealizableBetsInstructionDataArgs = {};

export function getSettleRealizableBetsInstructionDataEncoder(): Encoder<SettleRealizableBetsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: SETTLE_REALIZABLE_BETS_DISCRIMINATOR,
    }),
  );
}

export function getSettleRealizableBetsInstructionDataDecoder(): Decoder<SettleRealizableBetsInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getSettleRealizableBetsInstructionDataCodec(): Codec<
  SettleRealizableBetsInstructionDataArgs,
  SettleRealizableBetsInstructionData
> {
  return combineCodec(
    getSettleRealizableBetsInstructionDataEncoder(),
    getSettleRealizableBetsInstructionDataDecoder(),
  );
}

export type SettleRealizableBetsInput<
  TAccountGlobalGameState extends string = string,
  TAccountTreasury extends string = string,
  TAccountAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** Authority account */
  authority: TransactionSigner<TAccountAuthority>;
};

export function getSettleRealizableBetsInstruction<
  TAccountGlobalGameState extends string,
  TAccountTreasury extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: SettleRealizableBetsInput<
    TAccountGlobalGameState,
    TAccountTreasury,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): SettleRealizableBetsInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountTreasury,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getSettleRealizableBetsInstructionDataEncoder().encode({}),
  } as SettleRealizableBetsInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountTreasury,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedSettleRealizableBetsInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Treasury account */
    treasury: TAccountMetas[1];
    /** Authority account */
    authority: TAccountMetas[2];
  };
  data: SettleRealizableBetsInstructionData;
};

export function parseSettleRealizableBetsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedSettleRealizableBetsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      treasury: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getSettleRealizableBetsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
