/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const START_BETTING_PHASE_DISCRIMINATOR = 12;

export function getStartBettingPhaseDiscriminatorBytes() {
  return getU8Encoder().encode(START_BETTING_PHASE_DISCRIMINATOR);
}

export type StartBettingPhaseInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountRngState extends string | IAccountMeta<string> = string,
  TAccountRngAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountRngState extends string
        ? ReadonlyAccount<TAccountRngState>
        : TAccountRngState,
      TAccountRngAuthority extends string
        ? ReadonlySignerAccount<TAccountRngAuthority> &
            IAccountSignerMeta<TAccountRngAuthority>
        : TAccountRngAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type StartBettingPhaseInstructionData = { discriminator: number };

export type StartBettingPhaseInstructionDataArgs = {};

export function getStartBettingPhaseInstructionDataEncoder(): Encoder<StartBettingPhaseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: START_BETTING_PHASE_DISCRIMINATOR }),
  );
}

export function getStartBettingPhaseInstructionDataDecoder(): Decoder<StartBettingPhaseInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getStartBettingPhaseInstructionDataCodec(): Codec<
  StartBettingPhaseInstructionDataArgs,
  StartBettingPhaseInstructionData
> {
  return combineCodec(
    getStartBettingPhaseInstructionDataEncoder(),
    getStartBettingPhaseInstructionDataDecoder(),
  );
}

export type StartBettingPhaseInput<
  TAccountGlobalGameState extends string = string,
  TAccountRngState extends string = string,
  TAccountRngAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** RNG state account */
  rngState: Address<TAccountRngState>;
  /** RNG authority */
  rngAuthority: TransactionSigner<TAccountRngAuthority>;
};

export function getStartBettingPhaseInstruction<
  TAccountGlobalGameState extends string,
  TAccountRngState extends string,
  TAccountRngAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: StartBettingPhaseInput<
    TAccountGlobalGameState,
    TAccountRngState,
    TAccountRngAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): StartBettingPhaseInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountRngState,
  TAccountRngAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    rngState: { value: input.rngState ?? null, isWritable: false },
    rngAuthority: { value: input.rngAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.rngState),
      getAccountMeta(accounts.rngAuthority),
    ],
    programAddress,
    data: getStartBettingPhaseInstructionDataEncoder().encode({}),
  } as StartBettingPhaseInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountRngState,
    TAccountRngAuthority
  >;

  return instruction;
}

export type ParsedStartBettingPhaseInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** RNG state account */
    rngState: TAccountMetas[1];
    /** RNG authority */
    rngAuthority: TAccountMetas[2];
  };
  data: StartBettingPhaseInstructionData;
};

export function parseStartBettingPhaseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedStartBettingPhaseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      rngState: getNextAccount(),
      rngAuthority: getNextAccount(),
    },
    data: getStartBettingPhaseInstructionDataDecoder().decode(instruction.data),
  };
}
