/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_PLAYER_TOURNAMENT_DISCRIMINATOR = 28;

export function getUpdatePlayerTournamentDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_PLAYER_TOURNAMENT_DISCRIMINATOR);
}

export type UpdatePlayerTournamentInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountPlayerState extends string | IAccountMeta<string> = string,
  TAccountTournamentProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPlayerState extends string
        ? WritableAccount<TAccountPlayerState>
        : TAccountPlayerState,
      TAccountTournamentProgram extends string
        ? ReadonlySignerAccount<TAccountTournamentProgram> &
            IAccountSignerMeta<TAccountTournamentProgram>
        : TAccountTournamentProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UpdatePlayerTournamentInstructionData = { discriminator: number };

export type UpdatePlayerTournamentInstructionDataArgs = {};

export function getUpdatePlayerTournamentInstructionDataEncoder(): Encoder<UpdatePlayerTournamentInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: UPDATE_PLAYER_TOURNAMENT_DISCRIMINATOR,
    }),
  );
}

export function getUpdatePlayerTournamentInstructionDataDecoder(): Decoder<UpdatePlayerTournamentInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getUpdatePlayerTournamentInstructionDataCodec(): Codec<
  UpdatePlayerTournamentInstructionDataArgs,
  UpdatePlayerTournamentInstructionData
> {
  return combineCodec(
    getUpdatePlayerTournamentInstructionDataEncoder(),
    getUpdatePlayerTournamentInstructionDataDecoder(),
  );
}

export type UpdatePlayerTournamentInput<
  TAccountPlayerState extends string = string,
  TAccountTournamentProgram extends string = string,
> = {
  /** Player state account */
  playerState: Address<TAccountPlayerState>;
  /** Tournament program */
  tournamentProgram: TransactionSigner<TAccountTournamentProgram>;
};

export function getUpdatePlayerTournamentInstruction<
  TAccountPlayerState extends string,
  TAccountTournamentProgram extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: UpdatePlayerTournamentInput<
    TAccountPlayerState,
    TAccountTournamentProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UpdatePlayerTournamentInstruction<
  TProgramAddress,
  TAccountPlayerState,
  TAccountTournamentProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    playerState: { value: input.playerState ?? null, isWritable: true },
    tournamentProgram: {
      value: input.tournamentProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.playerState),
      getAccountMeta(accounts.tournamentProgram),
    ],
    programAddress,
    data: getUpdatePlayerTournamentInstructionDataEncoder().encode({}),
  } as UpdatePlayerTournamentInstruction<
    TProgramAddress,
    TAccountPlayerState,
    TAccountTournamentProgram
  >;

  return instruction;
}

export type ParsedUpdatePlayerTournamentInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Player state account */
    playerState: TAccountMetas[0];
    /** Tournament program */
    tournamentProgram: TAccountMetas[1];
  };
  data: UpdatePlayerTournamentInstructionData;
};

export function parseUpdatePlayerTournamentInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedUpdatePlayerTournamentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      playerState: getNextAccount(),
      tournamentProgram: getNextAccount(),
    },
    data: getUpdatePlayerTournamentInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
