/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_AUTHORITY_DISCRIMINATOR = 18;

export function getUpdateAuthorityDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_AUTHORITY_DISCRIMINATOR);
}

export type UpdateAuthorityInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountCurrentAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountGlobalGameState extends string
        ? WritableAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountCurrentAuthority extends string
        ? ReadonlySignerAccount<TAccountCurrentAuthority> &
            IAccountSignerMeta<TAccountCurrentAuthority>
        : TAccountCurrentAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateAuthorityInstructionData = { discriminator: number };

export type UpdateAuthorityInstructionDataArgs = {};

export function getUpdateAuthorityInstructionDataEncoder(): Encoder<UpdateAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: UPDATE_AUTHORITY_DISCRIMINATOR }),
  );
}

export function getUpdateAuthorityInstructionDataDecoder(): Decoder<UpdateAuthorityInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getUpdateAuthorityInstructionDataCodec(): Codec<
  UpdateAuthorityInstructionDataArgs,
  UpdateAuthorityInstructionData
> {
  return combineCodec(
    getUpdateAuthorityInstructionDataEncoder(),
    getUpdateAuthorityInstructionDataDecoder(),
  );
}

export type UpdateAuthorityInput<
  TAccountGlobalGameState extends string = string,
  TAccountCurrentAuthority extends string = string,
> = {
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Current authority */
  currentAuthority: TransactionSigner<TAccountCurrentAuthority>;
};

export function getUpdateAuthorityInstruction<
  TAccountGlobalGameState extends string,
  TAccountCurrentAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: UpdateAuthorityInput<
    TAccountGlobalGameState,
    TAccountCurrentAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateAuthorityInstruction<
  TProgramAddress,
  TAccountGlobalGameState,
  TAccountCurrentAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalGameState: { value: input.globalGameState ?? null, isWritable: true },
    currentAuthority: {
      value: input.currentAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.currentAuthority),
    ],
    programAddress,
    data: getUpdateAuthorityInstructionDataEncoder().encode({}),
  } as UpdateAuthorityInstruction<
    TProgramAddress,
    TAccountGlobalGameState,
    TAccountCurrentAuthority
  >;

  return instruction;
}

export type ParsedUpdateAuthorityInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Global game state account */
    globalGameState: TAccountMetas[0];
    /** Current authority */
    currentAuthority: TAccountMetas[1];
  };
  data: UpdateAuthorityInstructionData;
};

export function parseUpdateAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedUpdateAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalGameState: getNextAccount(),
      currentAuthority: getNextAccount(),
    },
    data: getUpdateAuthorityInstructionDataDecoder().decode(instruction.data),
  };
}
