/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_TREASURY_AUTHORITY_DISCRIMINATOR = 30;

export function getUpdateTreasuryAuthorityDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_TREASURY_AUTHORITY_DISCRIMINATOR);
}

export type UpdateTreasuryAuthorityInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountCurrentAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountCurrentAuthority extends string
        ? ReadonlySignerAccount<TAccountCurrentAuthority> &
            IAccountSignerMeta<TAccountCurrentAuthority>
        : TAccountCurrentAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateTreasuryAuthorityInstructionData = { discriminator: number };

export type UpdateTreasuryAuthorityInstructionDataArgs = {};

export function getUpdateTreasuryAuthorityInstructionDataEncoder(): Encoder<UpdateTreasuryAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: UPDATE_TREASURY_AUTHORITY_DISCRIMINATOR,
    }),
  );
}

export function getUpdateTreasuryAuthorityInstructionDataDecoder(): Decoder<UpdateTreasuryAuthorityInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getUpdateTreasuryAuthorityInstructionDataCodec(): Codec<
  UpdateTreasuryAuthorityInstructionDataArgs,
  UpdateTreasuryAuthorityInstructionData
> {
  return combineCodec(
    getUpdateTreasuryAuthorityInstructionDataEncoder(),
    getUpdateTreasuryAuthorityInstructionDataDecoder(),
  );
}

export type UpdateTreasuryAuthorityInput<
  TAccountTreasury extends string = string,
  TAccountCurrentAuthority extends string = string,
> = {
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** Current authority */
  currentAuthority: TransactionSigner<TAccountCurrentAuthority>;
};

export function getUpdateTreasuryAuthorityInstruction<
  TAccountTreasury extends string,
  TAccountCurrentAuthority extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: UpdateTreasuryAuthorityInput<
    TAccountTreasury,
    TAccountCurrentAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateTreasuryAuthorityInstruction<
  TProgramAddress,
  TAccountTreasury,
  TAccountCurrentAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    treasury: { value: input.treasury ?? null, isWritable: true },
    currentAuthority: {
      value: input.currentAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.currentAuthority),
    ],
    programAddress,
    data: getUpdateTreasuryAuthorityInstructionDataEncoder().encode({}),
  } as UpdateTreasuryAuthorityInstruction<
    TProgramAddress,
    TAccountTreasury,
    TAccountCurrentAuthority
  >;

  return instruction;
}

export type ParsedUpdateTreasuryAuthorityInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Treasury account */
    treasury: TAccountMetas[0];
    /** Current authority */
    currentAuthority: TAccountMetas[1];
  };
  data: UpdateTreasuryAuthorityInstructionData;
};

export function parseUpdateTreasuryAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedUpdateTreasuryAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      treasury: getNextAccount(),
      currentAuthority: getNextAccount(),
    },
    data: getUpdateTreasuryAuthorityInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
