/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_TREASURY_PARAMETERS_DISCRIMINATOR = 31;

export function getUpdateTreasuryParametersDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_TREASURY_PARAMETERS_DISCRIMINATOR);
}

export type UpdateTreasuryParametersInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountGlobalGameState extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountGlobalGameState extends string
        ? ReadonlyAccount<TAccountGlobalGameState>
        : TAccountGlobalGameState,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateTreasuryParametersInstructionData = { discriminator: number };

export type UpdateTreasuryParametersInstructionDataArgs = {};

export function getUpdateTreasuryParametersInstructionDataEncoder(): Encoder<UpdateTreasuryParametersInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: UPDATE_TREASURY_PARAMETERS_DISCRIMINATOR,
    }),
  );
}

export function getUpdateTreasuryParametersInstructionDataDecoder(): Decoder<UpdateTreasuryParametersInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getUpdateTreasuryParametersInstructionDataCodec(): Codec<
  UpdateTreasuryParametersInstructionDataArgs,
  UpdateTreasuryParametersInstructionData
> {
  return combineCodec(
    getUpdateTreasuryParametersInstructionDataEncoder(),
    getUpdateTreasuryParametersInstructionDataDecoder(),
  );
}

export type UpdateTreasuryParametersInput<
  TAccountTreasury extends string = string,
  TAccountGlobalGameState extends string = string,
  TAccountAdmin extends string = string,
> = {
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** Global game state account */
  globalGameState: Address<TAccountGlobalGameState>;
  /** Admin authority */
  admin: TransactionSigner<TAccountAdmin>;
};

export function getUpdateTreasuryParametersInstruction<
  TAccountTreasury extends string,
  TAccountGlobalGameState extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: UpdateTreasuryParametersInput<
    TAccountTreasury,
    TAccountGlobalGameState,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateTreasuryParametersInstruction<
  TProgramAddress,
  TAccountTreasury,
  TAccountGlobalGameState,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    treasury: { value: input.treasury ?? null, isWritable: true },
    globalGameState: {
      value: input.globalGameState ?? null,
      isWritable: false,
    },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.globalGameState),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getUpdateTreasuryParametersInstructionDataEncoder().encode({}),
  } as UpdateTreasuryParametersInstruction<
    TProgramAddress,
    TAccountTreasury,
    TAccountGlobalGameState,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedUpdateTreasuryParametersInstruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Treasury account */
    treasury: TAccountMetas[0];
    /** Global game state account */
    globalGameState: TAccountMetas[1];
    /** Admin authority */
    admin: TAccountMetas[2];
  };
  data: UpdateTreasuryParametersInstructionData;
};

export function parseUpdateTreasuryParametersInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedUpdateTreasuryParametersInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      treasury: getNextAccount(),
      globalGameState: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getUpdateTreasuryParametersInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
