/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { CRAPS_PINOCCHIO_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const WITHDRAW_V2_DISCRIMINATOR = 5;

export function getWithdrawV2DiscriminatorBytes() {
  return getU8Encoder().encode(WITHDRAW_V2_DISCRIMINATOR);
}

export type WithdrawV2Instruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountTreasury extends string | IAccountMeta<string> = string,
  TAccountPlayerState extends string | IAccountMeta<string> = string,
  TAccountTreasuryTokenAccount extends string | IAccountMeta<string> = string,
  TAccountPlayerTokenAccount extends string | IAccountMeta<string> = string,
  TAccountPlayer extends string | IAccountMeta<string> = string,
  TAccountTreasuryAuthority extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountPlayerState extends string
        ? WritableAccount<TAccountPlayerState>
        : TAccountPlayerState,
      TAccountTreasuryTokenAccount extends string
        ? WritableAccount<TAccountTreasuryTokenAccount>
        : TAccountTreasuryTokenAccount,
      TAccountPlayerTokenAccount extends string
        ? WritableAccount<TAccountPlayerTokenAccount>
        : TAccountPlayerTokenAccount,
      TAccountPlayer extends string
        ? ReadonlySignerAccount<TAccountPlayer> &
            IAccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountTreasuryAuthority extends string
        ? ReadonlyAccount<TAccountTreasuryAuthority>
        : TAccountTreasuryAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawV2InstructionData = { discriminator: number };

export type WithdrawV2InstructionDataArgs = {};

export function getWithdrawV2InstructionDataEncoder(): Encoder<WithdrawV2InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: WITHDRAW_V2_DISCRIMINATOR }),
  );
}

export function getWithdrawV2InstructionDataDecoder(): Decoder<WithdrawV2InstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getWithdrawV2InstructionDataCodec(): Codec<
  WithdrawV2InstructionDataArgs,
  WithdrawV2InstructionData
> {
  return combineCodec(
    getWithdrawV2InstructionDataEncoder(),
    getWithdrawV2InstructionDataDecoder(),
  );
}

export type WithdrawV2Input<
  TAccountTreasury extends string = string,
  TAccountPlayerState extends string = string,
  TAccountTreasuryTokenAccount extends string = string,
  TAccountPlayerTokenAccount extends string = string,
  TAccountPlayer extends string = string,
  TAccountTreasuryAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Treasury account */
  treasury: Address<TAccountTreasury>;
  /** Player state account */
  playerState: Address<TAccountPlayerState>;
  /** Treasury's token account */
  treasuryTokenAccount: Address<TAccountTreasuryTokenAccount>;
  /** Player's token account */
  playerTokenAccount: Address<TAccountPlayerTokenAccount>;
  /** Player account */
  player: TransactionSigner<TAccountPlayer>;
  /** Treasury authority */
  treasuryAuthority: Address<TAccountTreasuryAuthority>;
  /** Token program */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getWithdrawV2Instruction<
  TAccountTreasury extends string,
  TAccountPlayerState extends string,
  TAccountTreasuryTokenAccount extends string,
  TAccountPlayerTokenAccount extends string,
  TAccountPlayer extends string,
  TAccountTreasuryAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
>(
  input: WithdrawV2Input<
    TAccountTreasury,
    TAccountPlayerState,
    TAccountTreasuryTokenAccount,
    TAccountPlayerTokenAccount,
    TAccountPlayer,
    TAccountTreasuryAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawV2Instruction<
  TProgramAddress,
  TAccountTreasury,
  TAccountPlayerState,
  TAccountTreasuryTokenAccount,
  TAccountPlayerTokenAccount,
  TAccountPlayer,
  TAccountTreasuryAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CRAPS_PINOCCHIO_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    treasury: { value: input.treasury ?? null, isWritable: true },
    playerState: { value: input.playerState ?? null, isWritable: true },
    treasuryTokenAccount: {
      value: input.treasuryTokenAccount ?? null,
      isWritable: true,
    },
    playerTokenAccount: {
      value: input.playerTokenAccount ?? null,
      isWritable: true,
    },
    player: { value: input.player ?? null, isWritable: false },
    treasuryAuthority: {
      value: input.treasuryAuthority ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.playerState),
      getAccountMeta(accounts.treasuryTokenAccount),
      getAccountMeta(accounts.playerTokenAccount),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.treasuryAuthority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getWithdrawV2InstructionDataEncoder().encode({}),
  } as WithdrawV2Instruction<
    TProgramAddress,
    TAccountTreasury,
    TAccountPlayerState,
    TAccountTreasuryTokenAccount,
    TAccountPlayerTokenAccount,
    TAccountPlayer,
    TAccountTreasuryAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedWithdrawV2Instruction<
  TProgram extends string = typeof CRAPS_PINOCCHIO_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Treasury account */
    treasury: TAccountMetas[0];
    /** Player state account */
    playerState: TAccountMetas[1];
    /** Treasury's token account */
    treasuryTokenAccount: TAccountMetas[2];
    /** Player's token account */
    playerTokenAccount: TAccountMetas[3];
    /** Player account */
    player: TAccountMetas[4];
    /** Treasury authority */
    treasuryAuthority: TAccountMetas[5];
    /** Token program */
    tokenProgram: TAccountMetas[6];
  };
  data: WithdrawV2InstructionData;
};

export function parseWithdrawV2Instruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedWithdrawV2Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      treasury: getNextAccount(),
      playerState: getNextAccount(),
      treasuryTokenAccount: getNextAccount(),
      playerTokenAccount: getNextAccount(),
      player: getNextAccount(),
      treasuryAuthority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getWithdrawV2InstructionDataDecoder().decode(instruction.data),
  };
}
