/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedDecrementInstruction,
  type ParsedIncrementInstruction,
  type ParsedInitializeInstruction,
  type ParsedResetInstruction,
  type ParsedSetValueInstruction,
} from '../instructions';

export const HELIUS_TEST_PROGRAM_ADDRESS =
  'CSaFvFwbwgL1ER61GjJ5RojtoAMFx11JmPsbR68RgT1A' as Address<'CSaFvFwbwgL1ER61GjJ5RojtoAMFx11JmPsbR68RgT1A'>;

export enum HeliusTestAccount {
  Counter,
}

export enum HeliusTestInstruction {
  Initialize,
  Increment,
  Decrement,
  SetValue,
  Reset,
}

export function identifyHeliusTestInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): HeliusTestInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return HeliusTestInstruction.Initialize;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return HeliusTestInstruction.Increment;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return HeliusTestInstruction.Decrement;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return HeliusTestInstruction.SetValue;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return HeliusTestInstruction.Reset;
  }
  throw new Error(
    'The provided instruction could not be identified as a heliusTest instruction.',
  );
}

export type ParsedHeliusTestInstruction<
  TProgram extends string = 'CSaFvFwbwgL1ER61GjJ5RojtoAMFx11JmPsbR68RgT1A',
> =
  | ({
      instructionType: HeliusTestInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: HeliusTestInstruction.Increment;
    } & ParsedIncrementInstruction<TProgram>)
  | ({
      instructionType: HeliusTestInstruction.Decrement;
    } & ParsedDecrementInstruction<TProgram>)
  | ({
      instructionType: HeliusTestInstruction.SetValue;
    } & ParsedSetValueInstruction<TProgram>)
  | ({
      instructionType: HeliusTestInstruction.Reset;
    } & ParsedResetInstruction<TProgram>);
