/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreatePdaInstruction,
  type ParsedGetPdaInstruction,
} from '../instructions';

export const TRANSFER_SOL_PROGRAM_ADDRESS =
  'CyfYCCieitUtiuYaqowEELiYnPwQunzTyC1dsSQrH2ZC' as Address<'CyfYCCieitUtiuYaqowEELiYnPwQunzTyC1dsSQrH2ZC'>;

export enum TransferSolAccount {
  Favorites,
}

export enum TransferSolInstruction {
  CreatePda,
  GetPda,
}

export function identifyTransferSolInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): TransferSolInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return TransferSolInstruction.CreatePda;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return TransferSolInstruction.GetPda;
  }
  throw new Error(
    'The provided instruction could not be identified as a transferSol instruction.',
  );
}

export type ParsedTransferSolInstruction<
  TProgram extends string = 'CyfYCCieitUtiuYaqowEELiYnPwQunzTyC1dsSQrH2ZC',
> =
  | ({
      instructionType: TransferSolInstruction.CreatePda;
    } & ParsedCreatePdaInstruction<TProgram>)
  | ({
      instructionType: TransferSolInstruction.GetPda;
    } & ParsedGetPdaInstruction<TProgram>);
