/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { CLOSE_ACCOUNT_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CREATE_USER_DISCRIMINATOR = 0;

export function getCreateUserDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_USER_DISCRIMINATOR);
}

export type CreateUserInstruction<
  TProgram extends string = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountTargetAccount extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountTargetAccount extends string
        ? WritableAccount<TAccountTargetAccount>
        : TAccountTargetAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateUserInstructionData = {
  discriminator: number;
  /** The name of the user to create */
  name: string;
};

export type CreateUserInstructionDataArgs = {
  /** The name of the user to create */
  name: string;
};

export function getCreateUserInstructionDataEncoder(): Encoder<CreateUserInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['name', fixEncoderSize(getUtf8Encoder(), 64)],
    ]),
    (value) => ({ ...value, discriminator: 0 }),
  );
}

export function getCreateUserInstructionDataDecoder(): Decoder<CreateUserInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['name', fixDecoderSize(getUtf8Decoder(), 64)],
  ]);
}

export function getCreateUserInstructionDataCodec(): Codec<
  CreateUserInstructionDataArgs,
  CreateUserInstructionData
> {
  return combineCodec(
    getCreateUserInstructionDataEncoder(),
    getCreateUserInstructionDataDecoder(),
  );
}

export type CreateUserInput<
  TAccountPayer extends string = string,
  TAccountTargetAccount extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The account that will pay for the transaction */
  payer: TransactionSigner<TAccountPayer>;
  /** The account to create */
  targetAccount: Address<TAccountTargetAccount>;
  /** System Program used to open our new account */
  systemProgram?: Address<TAccountSystemProgram>;
  name: CreateUserInstructionDataArgs['name'];
};

export function getCreateUserInstruction<
  TAccountPayer extends string,
  TAccountTargetAccount extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS,
>(
  input: CreateUserInput<
    TAccountPayer,
    TAccountTargetAccount,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateUserInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountTargetAccount,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? CLOSE_ACCOUNT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    targetAccount: { value: input.targetAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.targetAccount),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCreateUserInstructionDataEncoder().encode(
      args as CreateUserInstructionDataArgs,
    ),
  } as CreateUserInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountTargetAccount,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedCreateUserInstruction<
  TProgram extends string = typeof CLOSE_ACCOUNT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The account that will pay for the transaction */
    payer: TAccountMetas[0];
    /** The account to create */
    targetAccount: TAccountMetas[1];
    /** System Program used to open our new account */
    systemProgram: TAccountMetas[2];
  };
  data: CreateUserInstructionData;
};

export function parseCreateUserInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedCreateUserInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      targetAccount: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateUserInstructionDataDecoder().decode(instruction.data),
  };
}
