/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { TEST_COUNTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESET_DISCRIMINATOR = 4;

export function getResetDiscriminatorBytes() {
  return getU8Encoder().encode(RESET_DISCRIMINATOR);
}

export type ResetInstruction<
  TProgram extends string = typeof TEST_COUNTER_PROGRAM_ADDRESS,
  TAccountTestCounter extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTestCounter extends string
        ? WritableAccount<TAccountTestCounter>
        : TAccountTestCounter,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ResetInstructionData = { discriminator: number };

export type ResetInstructionDataArgs = {};

export function getResetInstructionDataEncoder(): Encoder<ResetInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: RESET_DISCRIMINATOR }),
  );
}

export function getResetInstructionDataDecoder(): Decoder<ResetInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getResetInstructionDataCodec(): Codec<
  ResetInstructionDataArgs,
  ResetInstructionData
> {
  return combineCodec(
    getResetInstructionDataEncoder(),
    getResetInstructionDataDecoder(),
  );
}

export type ResetInput<
  TAccountTestCounter extends string = string,
  TAccountAuthority extends string = string,
> = {
  /** Counter account to reset */
  testCounter: Address<TAccountTestCounter>;
  /** Authority account */
  authority: TransactionSigner<TAccountAuthority>;
};

export function getResetInstruction<
  TAccountTestCounter extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof TEST_COUNTER_PROGRAM_ADDRESS,
>(
  input: ResetInput<TAccountTestCounter, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): ResetInstruction<TProgramAddress, TAccountTestCounter, TAccountAuthority> {
  // Program address.
  const programAddress = config?.programAddress ?? TEST_COUNTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    testCounter: { value: input.testCounter ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.testCounter),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getResetInstructionDataEncoder().encode({}),
  } as ResetInstruction<
    TProgramAddress,
    TAccountTestCounter,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedResetInstruction<
  TProgram extends string = typeof TEST_COUNTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Counter account to reset */
    testCounter: TAccountMetas[0];
    /** Authority account */
    authority: TAccountMetas[1];
  };
  data: ResetInstructionData;
};

export function parseResetInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedResetInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      testCounter: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getResetInstructionDataDecoder().decode(instruction.data),
  };
}
