/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum MutationType {
  INCREASE,
  DECREASE,
}

export type MutationTypeArgs = MutationType;

export function getMutationTypeEncoder(): Encoder<MutationTypeArgs> {
  return getEnumEncoder(MutationType);
}

export function getMutationTypeDecoder(): Decoder<MutationType> {
  return getEnumDecoder(MutationType);
}

export function getMutationTypeCodec(): Codec<MutationTypeArgs, MutationType> {
  return combineCodec(getMutationTypeEncoder(), getMutationTypeDecoder());
}
