/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { type ParsedCreateInstruction } from '../instructions';

export const COUNTER_PROGRAM_ADDRESS =
  '8mqZdKKFP1rLWGJk8BtwV88t5YHHfF8v5rQbL9cEqrQx' as Address<'8mqZdKKFP1rLWGJk8BtwV88t5YHHfF8v5rQbL9cEqrQx'>;

export enum CounterAccount {
  AddressInfo,
}

export enum CounterInstruction {
  Create,
}

export function identifyCounterInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CounterInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return CounterInstruction.Create;
  }
  throw new Error(
    'The provided instruction could not be identified as a counter instruction.',
  );
}

export type ParsedCounterInstruction<
  TProgram extends string = '8mqZdKKFP1rLWGJk8BtwV88t5YHHfF8v5rQbL9cEqrQx',
> = {
  instructionType: CounterInstruction.Create;
} & ParsedCreateInstruction<TProgram>;
